# These properties should be in the infrastructure layer, but I couldn't get them imported from there.
spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 15
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 4096
          plan_parameter_metadata_max_size: 128
  datasource:
    hikari:
      auto-commit: false
      minimum-idle: 0
      maximum-pool-size: 40
      max-lifetime: 600000
      transaction-isolation: TRANSACTION_READ_COMMITTED
      datasource-properties:
        useServerPrepStmts: false
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 1024
server:
  shutdown: graceful
