name: Build & Test

on:
  push:
    branches: [ "main", "release/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        id: setup-java
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Cache Gradle cache and builds
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ${{ github.workspace }}/**/build
          key: ${{ runner.os }}-gradle-build-${{ hashFiles('**/gradle-wrapper.properties') }}-${{ steps.setup-java.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-gradle-build-${{ hashFiles('**/gradle-wrapper.properties') }}-${{ steps.setup-java.outputs.version }}
      - run: echo `find . -type d -name build`
      - name: Cache Gradle wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build -PcreateReports
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ${{ github.workspace }}/**/build/test-results/*/*.xml
